### PR TITLE
Welcome Guide

### PR DESCRIPTION
**Pull request by simurai**
This PR will replace the current `welcome.md` files with a new spit pane.

On the left is the logo with some useful links and on the right is a guide that should help new users get to know Atom.

screen shot 2015-02-13 at 9 53 07 am

Expanded guide:

screen shot 2015-02-13 at 9 54 01 am

### CODE REVIEW

**Comment by benogle** [comment]
We should make sure this looks ok in the atom dark theme. I think that;s the default.

**Comment by simurai** [comment]
Atom dark:

screen shot 2015-02-13 at 10 47 47 am

I think it's ok. Maybe "Note" and "Next time" could be a bit brighter? Uses `@text-color-subtle`.

**Comment by SebastianSzturo** [comment]
Looks great and much more inviting!
I really liked the ``If you only remember one thing make it cmd-shift-P`` from the old welcome screen. I am one of the inpatient users that skip every help tutorial, but that line stayed in my mind until now.
You think there would a place for that in the new welcome screen?

**Comment by simurai** [comment]
@SebastianSzturo It is still there:

screen shot 2015-02-13 at 12 08 45 pm

But yeah, it's hidden behind an extra click. Not sure, it might also appear in the background tips.

**Comment by SebastianSzturo** [comment]
＠simurai Awesome! Really love that little atom window. :heart:

**Comment by lee-dohm** [comment]
Wow ... this looks great! Well done :beers:

**Comment by thomasjo** [comment]
Awesome work @simurai :sparkling_heart:

**Comment by simurai** [comment]
:bow:

+ @benogle who did the tricky parts.

**Comment by philipgiuliani** [comment]
WOW this is awesome! :+1:

**Comment by mattgraham** [comment]
Great work @simurai !

**Pull request merged**
