### PR TITLE
Change menu names for different platforms

### LINKED ISSUE #46: The guide points to a non-existent menu in Windows and Linux
The guide contains the following lines:
<strong>Next time:</strong> You can open your stylesheet from Menu > Atom.
<strong>Next time:</strong> You can open your init script from Menu > Atom.
<strong>Next time:</strong> You can open your snippets in Menu > Atom.

This points to the darwin.cson menu file here: https://github.com/atom/atom/tree/master/menus.
The menus for Windows and Linux however have this menu item placed in Menu > File. The guide should be changed according to the platform.

### PR DESCRIPTION
**Pull request by rbottema**
Fixes #46.

### CODE REVIEW

**Comment by benogle** [comment]
Seems legit. cc @atom/feedback

**Comment by maxbrunsfeld** [comment]
Is it really the `Edit` menu on linux? That's strange.

**Comment by lee-dohm** [comment]
Works for me :+1:

**Comment by rbottema** [comment]
See https://github.com/atom/atom/blob/master/menus/linux.cson for Linux menu: it's in Edit (yeah it's strange that it is in three different menus)

**Comment by maxbrunsfeld** [comment]
:+1:

**Comment by benogle** [comment]
Thanks!

**Pull request merged**
