### PR TITLE
Checkbox for the showOnStartup config

### PR DESCRIPTION
**Pull request by olmokramer**
Adds a checkbox to the welcome view that toggles the showOnStartup config.

### CODE REVIEW

**Comment by benogle** [comment]
Hey, can you explain your motivations for changing this?

**Comment by olmokramer** [comment]
[This discuss  thread](https://discuss.atom.io/t/atom-welcome-screen/15261/7) and another one that requested the same thing about a week ago

**Comment by benogle** [comment]
Ok, I'm on board for this change. I kind of want it to be unchecked by default, though. 

Also, I have some concerns with the analytics data. Currently the data gives us a nice window into what people do on initial startup. But I'm afraid the usage patterns would be different on subsequent displays. So when this ships, I want to split the analytics gathering between the new users and subsequent loads. 

Anyway, just saying that this might not ship for a couple weeks.

**Comment by olmokramer** [comment]
Those are some fair concerns. I'll see what I can do, at least about the default unchecked stat, I'll leave the analytics part up to you guys

**Comment by olmokramer** [comment]
I've made it so the checkbox is unchecked by default now :)

**Comment by simurai** [comment]
I like this suggestion too. I think I've seen some other applications do the same. And I would even tend to have it enabled by default. A new user might not see the checkbox and miss the chance to enable it. When it's enabled by default, a user can keep it until it gets annoying or the guide is not needed anymore.

Good point about splitting stats between truly new user and returning one.

**Comment by thedaniel** [comment]
> And I would even tend to have it enabled by default.

I agree with this, it's not just a fluffy "welcome to atom" page, it currently leads into 7 different common user behaviors (likely more than a user will likely explore in their first session IMO), and it would be useful to show until a user is ready to take the training wheels off.

**Comment by benogle** [comment]
Ok, down to leave it checked by default.

**Comment by mnquintana** [comment]
@benogle How does this look to you now?

I'm wondering if it would be worth adding a spec for this.

**Comment by benogle** [comment]
Yeah, a spec for this would be really nice.

**Comment by benogle** [comment]
Also, my initial concern with splitting the analytics data needs to be addressed before this can be merged.

**Comment by elifoster** [comment]
Any word on this?

**Comment by benogle** [comment]
What needs to happen is: 

* splitting the analytics on initial and subsequent opens
* specs

**Comment by damieng** [comment]
Is there any interesting in completing this PR (specs and analytics switch) - it's been inactive for 9 months.

**Comment by simurai** [comment]
I still think it's a good idea. 👍 It will keep showing the Welcome Guide until a user is enough familiar and doesn't want it anymore.

**Comment by schwarzskykorys** [comment]
Hello, i'm kid.

I want don't show on startup Telemetry Contents page, i added to init.coffe "atom.config.set 'welcome.showOnStartup', false".

**Comment by damieng** [comment]
@schwarzskykorys You can just check the little box on the welcome screen and it can set it for you.

**Pull request merged**
